HEX
: WRITE-ADC-CONFIG ADS1115.CONF_REG 2 BYTE-OFFSET LSHIFT + 3 I2CWRITE> ;
: READ-ADC-CONFIG ADS1115.CONF_REG 2 >I2CREAD ;
: READ-ADC-CONVR ADS1115.CONVR_REG 2 >I2CREAD ;
: CONTINUOUS-READ BEGIN RESET-I2C DUP READ-ADC-CONVR DUP @ U.0 OVER ! AGAIN ;
: CONTINUOUS-SINGLE-SHOT BEGIN RESET-I2C C3E3 WRITE-ADC-CONFIG RESET-I2C DUP READ-ADC-CONVR DUP @ U. 0 OVER ! AGAIN ;